import type { Metadata } from 'next';
import { Barlow, Fira_Sans, Inter } from 'next/font/google';

import './globals.css';

import NavigationBar from './components/Navigation/NavigationBar';
import Footer from './components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });
const barlow = Barlow({ weight: ['100', '500', '600'] });
const fira = Fira_Sans({ weight: '200' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`m-auto w-10/12 ${barlow.className}`}>
          <NavigationBar />
        <main className="max-width-7xl">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
